#!/bin/bash
#
# setup-validator.sh - Set up Solana C validator environment
#
# This script creates the necessary directories and configuration files
# for running the Solana C validator.
#

set -e

# Configuration
SOLANA_USER="${SOLANA_USER:-solana}"
SOLANA_HOME="${SOLANA_HOME:-/var/solana}"
LEDGER_PATH="${SOLANA_HOME}/ledger"
IDENTITY_PATH="${SOLANA_HOME}/identity.json"
CONFIG_PATH="${SOLANA_HOME}/validator.toml"
LOG_PATH="/var/log/solana"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root or with sudo"
        exit 1
    fi
}

# Create user if needed
create_user() {
    if ! id "$SOLANA_USER" &>/dev/null; then
        log_info "Creating user: $SOLANA_USER"
        useradd -r -s /bin/false -d "$SOLANA_HOME" "$SOLANA_USER"
    else
        log_info "User $SOLANA_USER already exists"
    fi
}

# Create directories
create_directories() {
    log_info "Creating directories..."

    mkdir -p "$SOLANA_HOME"
    mkdir -p "$LEDGER_PATH"
    mkdir -p "$LEDGER_PATH/snapshots"
    mkdir -p "$LEDGER_PATH/rocksdb"
    mkdir -p "$LOG_PATH"

    chown -R "$SOLANA_USER:$SOLANA_USER" "$SOLANA_HOME"
    chown -R "$SOLANA_USER:$SOLANA_USER" "$LOG_PATH"

    chmod 700 "$SOLANA_HOME"
    chmod 755 "$LEDGER_PATH"
    chmod 755 "$LOG_PATH"

    log_info "Created directories at $SOLANA_HOME"
}

# Generate identity keypair
generate_identity() {
    if [ -f "$IDENTITY_PATH" ]; then
        log_warn "Identity already exists at $IDENTITY_PATH"
        log_warn "Skipping identity generation"
        return
    fi

    log_info "Generating identity keypair..."

    # Generate a new Ed25519 keypair (64 bytes: 32 secret + 32 public)
    # This is a placeholder - in production, use solana-keygen
    if command -v solana-keygen &>/dev/null; then
        solana-keygen new --outfile "$IDENTITY_PATH" --no-passphrase
    else
        log_warn "solana-keygen not found, validator will generate ephemeral identity"
        echo '[]' > "$IDENTITY_PATH"  # Placeholder
    fi

    chown "$SOLANA_USER:$SOLANA_USER" "$IDENTITY_PATH"
    chmod 600 "$IDENTITY_PATH"

    log_info "Identity keypair created at $IDENTITY_PATH"
}

# Create configuration file
create_config() {
    if [ -f "$CONFIG_PATH" ]; then
        log_warn "Config already exists at $CONFIG_PATH"
        log_warn "Skipping config generation"
        return
    fi

    log_info "Creating configuration file..."

    cat > "$CONFIG_PATH" << EOF
# Solana C Validator Configuration
# Generated by setup-validator.sh

[identity]
keypair = "$IDENTITY_PATH"

[ledger]
path = "$LEDGER_PATH"
rocksdb_path = "$LEDGER_PATH/rocksdb"
snapshot_path = "$LEDGER_PATH/snapshots"

[network]
entrypoints = [
    "entrypoint.testnet.solana.com:8001"
]
gossip_port = 8001
tpu_port = 8003
tvu_port = 8004
rpc_port = 8899
enable_quic = true

[rpc]
enable = true
bind = "0.0.0.0"
port = 8899

[snapshots]
full_interval = 25000
incremental_interval = 5000

[logging]
level = "info"
format = "json"
file = "$LOG_PATH/validator.log"

[metrics]
enable = true
port = 9090
EOF

    chown "$SOLANA_USER:$SOLANA_USER" "$CONFIG_PATH"
    chmod 600 "$CONFIG_PATH"

    log_info "Configuration created at $CONFIG_PATH"
}

# Install systemd service
install_service() {
    log_info "Installing systemd service..."

    VALIDATOR_PATH="$(dirname "$0")/../build/bin/solana-validator"

    if [ ! -f "$VALIDATOR_PATH" ]; then
        VALIDATOR_PATH="/usr/local/bin/solana-validator"
    fi

    cat > /etc/systemd/system/solana-validator.service << EOF
[Unit]
Description=Solana C Validator
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$SOLANA_USER
Group=$SOLANA_USER
ExecStart=$VALIDATOR_PATH --config $CONFIG_PATH
Restart=on-failure
RestartSec=10
LimitNOFILE=1000000
LimitNPROC=1000000

# Security hardening
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true

# Logging
StandardOutput=append:$LOG_PATH/validator.log
StandardError=append:$LOG_PATH/validator.log

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log_info "Systemd service installed"
}

# Set up log rotation
setup_logrotate() {
    log_info "Setting up log rotation..."

    cat > /etc/logrotate.d/solana-validator << EOF
$LOG_PATH/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0640 $SOLANA_USER $SOLANA_USER
    sharedscripts
    postrotate
        systemctl kill -s HUP solana-validator 2>/dev/null || true
    endscript
}
EOF

    log_info "Log rotation configured"
}

# Print summary
print_summary() {
    echo ""
    echo "========================================"
    echo "Solana C Validator Setup Complete"
    echo "========================================"
    echo ""
    echo "Directories:"
    echo "  Home:      $SOLANA_HOME"
    echo "  Ledger:    $LEDGER_PATH"
    echo "  Logs:      $LOG_PATH"
    echo ""
    echo "Files:"
    echo "  Identity:  $IDENTITY_PATH"
    echo "  Config:    $CONFIG_PATH"
    echo ""
    echo "Commands:"
    echo "  Start:     sudo systemctl start solana-validator"
    echo "  Stop:      sudo systemctl stop solana-validator"
    echo "  Status:    sudo systemctl status solana-validator"
    echo "  Logs:      sudo journalctl -u solana-validator -f"
    echo "  Health:    curl http://localhost:8899/health"
    echo "  Metrics:   curl http://localhost:9090/metrics"
    echo ""
}

# Main
main() {
    log_info "Setting up Solana C Validator..."

    check_root
    create_user
    create_directories
    generate_identity
    create_config
    install_service
    setup_logrotate
    print_summary

    log_info "Setup complete!"
}

main "$@"
