# Dependencies.cmake - External dependency management

include(FindPkgConfig)

# Threading support (required)
find_package(Threads REQUIRED)

# jemalloc (required for production, optional for dev)
option(USE_JEMALLOC "Use jemalloc allocator" ON)
if(USE_JEMALLOC)
    pkg_check_modules(JEMALLOC jemalloc)
    if(JEMALLOC_FOUND)
        message(STATUS "Found jemalloc: ${JEMALLOC_LIBRARIES}")
        add_definitions(-DSOL_USE_JEMALLOC=1)
    else()
        # Try to find jemalloc manually
        find_library(JEMALLOC_LIBRARIES NAMES jemalloc)
        find_path(JEMALLOC_INCLUDE_DIRS NAMES jemalloc/jemalloc.h)
        if(JEMALLOC_LIBRARIES AND JEMALLOC_INCLUDE_DIRS)
            message(STATUS "Found jemalloc: ${JEMALLOC_LIBRARIES}")
            add_definitions(-DSOL_USE_JEMALLOC=1)
        else()
            message(WARNING "jemalloc not found, using system malloc")
            set(USE_JEMALLOC OFF)
            set(JEMALLOC_LIBRARIES "")
            set(JEMALLOC_INCLUDE_DIRS "")
        endif()
    endif()
else()
    set(JEMALLOC_LIBRARIES "")
    set(JEMALLOC_INCLUDE_DIRS "")
endif()

# OpenSSL (required for crypto)
find_package(OpenSSL)
if(OPENSSL_FOUND)
    message(STATUS "Found OpenSSL: ${OPENSSL_VERSION}")
else()
    message(STATUS "OpenSSL not found (will be needed for Phase 1)")
endif()

# zstd (required for snapshot compression)
pkg_check_modules(ZSTD libzstd)
if(ZSTD_FOUND)
    message(STATUS "Found zstd: ${ZSTD_VERSION}")
else()
    message(STATUS "zstd not found (will be needed for Phase 6)")
endif()

# lz4 (for fast compression)
pkg_check_modules(LZ4 liblz4)
if(LZ4_FOUND)
    message(STATUS "Found lz4: ${LZ4_VERSION}")
else()
    message(STATUS "lz4 not found (optional)")
endif()

# RocksDB (required for blockstore)
pkg_check_modules(ROCKSDB rocksdb)
if(NOT ROCKSDB_FOUND)
    # Try Homebrew paths on macOS
    if(APPLE)
        set(HOMEBREW_PREFIX "/opt/homebrew" CACHE PATH "Homebrew prefix")
        if(EXISTS "${HOMEBREW_PREFIX}/opt/rocksdb")
            set(ROCKSDB_FOUND TRUE)
            set(ROCKSDB_INCLUDE_DIRS "${HOMEBREW_PREFIX}/opt/rocksdb/include")
            set(ROCKSDB_LIBRARY_DIRS "${HOMEBREW_PREFIX}/opt/rocksdb/lib")
            set(ROCKSDB_LIBRARIES "-L${ROCKSDB_LIBRARY_DIRS} -lrocksdb")
            message(STATUS "Found RocksDB via Homebrew: ${HOMEBREW_PREFIX}/opt/rocksdb")
        endif()
    endif()
    # Try /usr/local (manual install)
    if(NOT ROCKSDB_FOUND)
        find_path(ROCKSDB_INCLUDE_DIRS NAMES rocksdb/c.h
            PATHS /usr/local/include /usr/include)
        find_library(ROCKSDB_LIB NAMES rocksdb
            PATHS /usr/local/lib /usr/lib)
        if(ROCKSDB_INCLUDE_DIRS AND ROCKSDB_LIB)
            set(ROCKSDB_FOUND TRUE)
            get_filename_component(ROCKSDB_LIBRARY_DIRS ${ROCKSDB_LIB} DIRECTORY)
            set(ROCKSDB_LIBRARIES ${ROCKSDB_LIB})
            message(STATUS "Found RocksDB: ${ROCKSDB_LIB}")
        endif()
    endif()
endif()
if(ROCKSDB_FOUND)
    message(STATUS "RocksDB: enabled")
else()
    message(STATUS "RocksDB: not found (persistent storage disabled)")
endif()

# libsodium (for Ed25519)
pkg_check_modules(SODIUM libsodium)
if(SODIUM_FOUND)
    message(STATUS "Found libsodium: ${SODIUM_VERSION}")
    # Make library directories available for linking
    link_directories(${SODIUM_LIBRARY_DIRS})
else()
    message(STATUS "libsodium not found (will be needed for Phase 1)")
endif()

# secp256k1 (for Ethereum signature recovery)
pkg_check_modules(SECP256K1 libsecp256k1)
if(SECP256K1_FOUND)
    message(STATUS "Found secp256k1: ${SECP256K1_VERSION}")
else()
    message(STATUS "secp256k1 not found (will be needed for Phase 1)")
endif()

# io_uring (Linux only, for async I/O)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    pkg_check_modules(URING liburing)
    if(URING_FOUND)
        message(STATUS "Found io_uring: ${URING_VERSION}")
        add_definitions(-DSOL_USE_IO_URING=1)
    else()
        message(STATUS "io_uring not found (will use epoll fallback)")
    endif()
endif()

# quiche (for QUIC transport) - typically built from source
# Try pkg-config first
pkg_check_modules(QUICHE quiche)
if(NOT QUICHE_FOUND)
    # Try to find library and header manually
    find_library(QUICHE_LIBRARY NAMES quiche
        PATHS /usr/local/lib /usr/lib
        PATH_SUFFIXES lib lib64)
    find_path(QUICHE_INCLUDE_DIR NAMES quiche.h
        PATHS /usr/local/include /usr/include)

    if(QUICHE_LIBRARY AND QUICHE_INCLUDE_DIR)
        set(QUICHE_FOUND TRUE)
        set(QUICHE_INCLUDE_DIRS ${QUICHE_INCLUDE_DIR})
        get_filename_component(QUICHE_LIBRARY_DIRS ${QUICHE_LIBRARY} DIRECTORY)
        set(QUICHE_LIBRARIES ${QUICHE_LIBRARY})
    endif()
endif()

if(QUICHE_FOUND)
    message(STATUS "quiche: enabled (${QUICHE_LIBRARIES})")
else()
    message(STATUS "quiche: not found (QUIC transport disabled)")
    message(STATUS "  To install: ./scripts/build-quiche.sh")
endif()

# Print dependency summary
message(STATUS "")
message(STATUS "=== Dependency Summary ===")
message(STATUS "  jemalloc:    ${USE_JEMALLOC}")
message(STATUS "  OpenSSL:     ${OPENSSL_FOUND}")
message(STATUS "  zstd:        ${ZSTD_FOUND}")
message(STATUS "  lz4:         ${LZ4_FOUND}")
message(STATUS "  RocksDB:     ${ROCKSDB_FOUND}")
message(STATUS "  quiche:      ${QUICHE_FOUND}")
message(STATUS "  libsodium:   ${SODIUM_FOUND}")
message(STATUS "  secp256k1:   ${SECP256K1_FOUND}")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "  io_uring:    ${URING_FOUND}")
endif()
message(STATUS "")
